/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FirmarSepaRouteImport } from './routes/firmar-sepa'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistroCallbackRouteImport } from './routes/registro_.callback'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTurnosRouteImport } from './routes/_authenticated/turnos'
import { Route as AuthenticatedTarifasRouteImport } from './routes/_authenticated/tarifas'
import { Route as AuthenticatedSesionesRouteImport } from './routes/_authenticated/sesiones'
import { Route as AuthenticatedRubricasRouteImport } from './routes/_authenticated/rubricas'
import { Route as AuthenticatedRemesasRouteImport } from './routes/_authenticated/remesas'
import { Route as AuthenticatedProfesoresRouteImport } from './routes/_authenticated/profesores'
import { Route as AuthenticatedPrestamosMaterialRouteImport } from './routes/_authenticated/prestamosMaterial'
import { Route as AuthenticatedMensajesAutomaticosRouteImport } from './routes/_authenticated/mensajesAutomaticos'
import { Route as AuthenticatedMatriculasRouteImport } from './routes/_authenticated/matriculas'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedIncidenciasRouteImport } from './routes/_authenticated/incidencias'
import { Route as AuthenticatedGruposRouteImport } from './routes/_authenticated/grupos'
import { Route as AuthenticatedFichajesRouteImport } from './routes/_authenticated/fichajes'
import { Route as AuthenticatedFacturasRouteImport } from './routes/_authenticated/facturas'
import { Route as AuthenticatedEvaluacionesRouteImport } from './routes/_authenticated/evaluaciones'
import { Route as AuthenticatedEspecialidadesRouteImport } from './routes/_authenticated/especialidades'
import { Route as AuthenticatedEscuelaRouteImport } from './routes/_authenticated/escuela'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComprasInternasRouteImport } from './routes/_authenticated/comprasInternas'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAusenciasRouteImport } from './routes/_authenticated/ausencias'
import { Route as AuthenticatedAulasRouteImport } from './routes/_authenticated/aulas'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAlumnosMatriculasRouteImport } from './routes/_authenticated/alumnosMatriculas'
import { Route as AuthenticatedAlumnosRouteImport } from './routes/_authenticated/alumnos'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedProfesoresMiPerfilRouteImport } from './routes/_authenticated/profesores.mi-perfil'
import { Route as AuthenticatedAppTurnosRouteImport } from './routes/_authenticated/app/turnos'
import { Route as AuthenticatedAppSesionesRouteImport } from './routes/_authenticated/app/sesiones'
import { Route as AuthenticatedAppPrestamosRouteImport } from './routes/_authenticated/app/prestamos'
import { Route as AuthenticatedAppPermisosRouteImport } from './routes/_authenticated/app/permisos'
import { Route as AuthenticatedAppIncidenciasRouteImport } from './routes/_authenticated/app/incidencias'
import { Route as AuthenticatedAppGruposRouteImport } from './routes/_authenticated/app/grupos'
import { Route as AuthenticatedAppFichajesRouteImport } from './routes/_authenticated/app/fichajes'
import { Route as AuthenticatedAppEvaluacionesRouteImport } from './routes/_authenticated/app/evaluaciones'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app/documentos'
import { Route as AuthenticatedAppDatosPersonalesRouteImport } from './routes/_authenticated/app/datos-personales'
import { Route as AuthenticatedAppArchivosRouteImport } from './routes/_authenticated/app/archivos'
import { Route as AuthenticatedAppAlumnosRouteImport } from './routes/_authenticated/app/alumnos'

const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmarSepaRoute = FirmarSepaRouteImport.update({
  id: '/firmar-sepa',
  path: '/firmar-sepa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroCallbackRoute = RegistroCallbackRouteImport.update({
  id: '/registro_/callback',
  path: '/registro/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTurnosRoute = AuthenticatedTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTarifasRoute = AuthenticatedTarifasRouteImport.update({
  id: '/tarifas',
  path: '/tarifas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSesionesRoute = AuthenticatedSesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRubricasRoute = AuthenticatedRubricasRouteImport.update({
  id: '/rubricas',
  path: '/rubricas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemesasRoute = AuthenticatedRemesasRouteImport.update({
  id: '/remesas',
  path: '/remesas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfesoresRoute = AuthenticatedProfesoresRouteImport.update({
  id: '/profesores',
  path: '/profesores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrestamosMaterialRoute =
  AuthenticatedPrestamosMaterialRouteImport.update({
    id: '/prestamosMaterial',
    path: '/prestamosMaterial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMensajesAutomaticosRoute =
  AuthenticatedMensajesAutomaticosRouteImport.update({
    id: '/mensajesAutomaticos',
    path: '/mensajesAutomaticos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatriculasRoute = AuthenticatedMatriculasRouteImport.update({
  id: '/matriculas',
  path: '/matriculas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidenciasRoute =
  AuthenticatedIncidenciasRouteImport.update({
    id: '/incidencias',
    path: '/incidencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGruposRoute = AuthenticatedGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFichajesRoute = AuthenticatedFichajesRouteImport.update({
  id: '/fichajes',
  path: '/fichajes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacturasRoute = AuthenticatedFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEvaluacionesRoute =
  AuthenticatedEvaluacionesRouteImport.update({
    id: '/evaluaciones',
    path: '/evaluaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEspecialidadesRoute =
  AuthenticatedEspecialidadesRouteImport.update({
    id: '/especialidades',
    path: '/especialidades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEscuelaRoute = AuthenticatedEscuelaRouteImport.update({
  id: '/escuela',
  path: '/escuela',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComprasInternasRoute =
  AuthenticatedComprasInternasRouteImport.update({
    id: '/comprasInternas',
    path: '/comprasInternas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAusenciasRoute = AuthenticatedAusenciasRouteImport.update({
  id: '/ausencias',
  path: '/ausencias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAulasRoute = AuthenticatedAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlumnosMatriculasRoute =
  AuthenticatedAlumnosMatriculasRouteImport.update({
    id: '/alumnosMatriculas',
    path: '/alumnosMatriculas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlumnosRoute = AuthenticatedAlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedProfesoresMiPerfilRoute =
  AuthenticatedProfesoresMiPerfilRouteImport.update({
    id: '/mi-perfil',
    path: '/mi-perfil',
    getParentRoute: () => AuthenticatedProfesoresRoute,
  } as any)
const AuthenticatedAppTurnosRoute = AuthenticatedAppTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSesionesRoute =
  AuthenticatedAppSesionesRouteImport.update({
    id: '/sesiones',
    path: '/sesiones',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPrestamosRoute =
  AuthenticatedAppPrestamosRouteImport.update({
    id: '/prestamos',
    path: '/prestamos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPermisosRoute =
  AuthenticatedAppPermisosRouteImport.update({
    id: '/permisos',
    path: '/permisos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIncidenciasRoute =
  AuthenticatedAppIncidenciasRouteImport.update({
    id: '/incidencias',
    path: '/incidencias',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGruposRoute = AuthenticatedAppGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFichajesRoute =
  AuthenticatedAppFichajesRouteImport.update({
    id: '/fichajes',
    path: '/fichajes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEvaluacionesRoute =
  AuthenticatedAppEvaluacionesRouteImport.update({
    id: '/evaluaciones',
    path: '/evaluaciones',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDatosPersonalesRoute =
  AuthenticatedAppDatosPersonalesRouteImport.update({
    id: '/datos-personales',
    path: '/datos-personales',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppArchivosRoute =
  AuthenticatedAppArchivosRouteImport.update({
    id: '/archivos',
    path: '/archivos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlumnosRoute = AuthenticatedAppAlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/firmar-sepa': typeof FirmarSepaRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/select-tenant': typeof SelectTenantRoute
  '/alumnos': typeof AuthenticatedAlumnosRoute
  '/alumnosMatriculas': typeof AuthenticatedAlumnosMatriculasRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/aulas': typeof AuthenticatedAulasRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comprasInternas': typeof AuthenticatedComprasInternasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/escuela': typeof AuthenticatedEscuelaRoute
  '/especialidades': typeof AuthenticatedEspecialidadesRoute
  '/evaluaciones': typeof AuthenticatedEvaluacionesRoute
  '/facturas': typeof AuthenticatedFacturasRoute
  '/fichajes': typeof AuthenticatedFichajesRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/matriculas': typeof AuthenticatedMatriculasRoute
  '/mensajesAutomaticos': typeof AuthenticatedMensajesAutomaticosRoute
  '/prestamosMaterial': typeof AuthenticatedPrestamosMaterialRoute
  '/profesores': typeof AuthenticatedProfesoresRouteWithChildren
  '/remesas': typeof AuthenticatedRemesasRoute
  '/rubricas': typeof AuthenticatedRubricasRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/tarifas': typeof AuthenticatedTarifasRoute
  '/turnos': typeof AuthenticatedTurnosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/registro/callback': typeof RegistroCallbackRoute
  '/app/alumnos': typeof AuthenticatedAppAlumnosRoute
  '/app/archivos': typeof AuthenticatedAppArchivosRoute
  '/app/datos-personales': typeof AuthenticatedAppDatosPersonalesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/evaluaciones': typeof AuthenticatedAppEvaluacionesRoute
  '/app/fichajes': typeof AuthenticatedAppFichajesRoute
  '/app/grupos': typeof AuthenticatedAppGruposRoute
  '/app/incidencias': typeof AuthenticatedAppIncidenciasRoute
  '/app/permisos': typeof AuthenticatedAppPermisosRoute
  '/app/prestamos': typeof AuthenticatedAppPrestamosRoute
  '/app/sesiones': typeof AuthenticatedAppSesionesRoute
  '/app/turnos': typeof AuthenticatedAppTurnosRoute
  '/profesores/mi-perfil': typeof AuthenticatedProfesoresMiPerfilRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firmar-sepa': typeof FirmarSepaRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/select-tenant': typeof SelectTenantRoute
  '/alumnos': typeof AuthenticatedAlumnosRoute
  '/alumnosMatriculas': typeof AuthenticatedAlumnosMatriculasRoute
  '/aulas': typeof AuthenticatedAulasRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comprasInternas': typeof AuthenticatedComprasInternasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/escuela': typeof AuthenticatedEscuelaRoute
  '/especialidades': typeof AuthenticatedEspecialidadesRoute
  '/evaluaciones': typeof AuthenticatedEvaluacionesRoute
  '/facturas': typeof AuthenticatedFacturasRoute
  '/fichajes': typeof AuthenticatedFichajesRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/matriculas': typeof AuthenticatedMatriculasRoute
  '/mensajesAutomaticos': typeof AuthenticatedMensajesAutomaticosRoute
  '/prestamosMaterial': typeof AuthenticatedPrestamosMaterialRoute
  '/profesores': typeof AuthenticatedProfesoresRouteWithChildren
  '/remesas': typeof AuthenticatedRemesasRoute
  '/rubricas': typeof AuthenticatedRubricasRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/tarifas': typeof AuthenticatedTarifasRoute
  '/turnos': typeof AuthenticatedTurnosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/registro/callback': typeof RegistroCallbackRoute
  '/app/alumnos': typeof AuthenticatedAppAlumnosRoute
  '/app/archivos': typeof AuthenticatedAppArchivosRoute
  '/app/datos-personales': typeof AuthenticatedAppDatosPersonalesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/evaluaciones': typeof AuthenticatedAppEvaluacionesRoute
  '/app/fichajes': typeof AuthenticatedAppFichajesRoute
  '/app/grupos': typeof AuthenticatedAppGruposRoute
  '/app/incidencias': typeof AuthenticatedAppIncidenciasRoute
  '/app/permisos': typeof AuthenticatedAppPermisosRoute
  '/app/prestamos': typeof AuthenticatedAppPrestamosRoute
  '/app/sesiones': typeof AuthenticatedAppSesionesRoute
  '/app/turnos': typeof AuthenticatedAppTurnosRoute
  '/profesores/mi-perfil': typeof AuthenticatedProfesoresMiPerfilRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/firmar-sepa': typeof FirmarSepaRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/select-tenant': typeof SelectTenantRoute
  '/_authenticated/alumnos': typeof AuthenticatedAlumnosRoute
  '/_authenticated/alumnosMatriculas': typeof AuthenticatedAlumnosMatriculasRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/aulas': typeof AuthenticatedAulasRoute
  '/_authenticated/ausencias': typeof AuthenticatedAusenciasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/comprasInternas': typeof AuthenticatedComprasInternasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/escuela': typeof AuthenticatedEscuelaRoute
  '/_authenticated/especialidades': typeof AuthenticatedEspecialidadesRoute
  '/_authenticated/evaluaciones': typeof AuthenticatedEvaluacionesRoute
  '/_authenticated/facturas': typeof AuthenticatedFacturasRoute
  '/_authenticated/fichajes': typeof AuthenticatedFichajesRoute
  '/_authenticated/grupos': typeof AuthenticatedGruposRoute
  '/_authenticated/incidencias': typeof AuthenticatedIncidenciasRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/matriculas': typeof AuthenticatedMatriculasRoute
  '/_authenticated/mensajesAutomaticos': typeof AuthenticatedMensajesAutomaticosRoute
  '/_authenticated/prestamosMaterial': typeof AuthenticatedPrestamosMaterialRoute
  '/_authenticated/profesores': typeof AuthenticatedProfesoresRouteWithChildren
  '/_authenticated/remesas': typeof AuthenticatedRemesasRoute
  '/_authenticated/rubricas': typeof AuthenticatedRubricasRoute
  '/_authenticated/sesiones': typeof AuthenticatedSesionesRoute
  '/_authenticated/tarifas': typeof AuthenticatedTarifasRoute
  '/_authenticated/turnos': typeof AuthenticatedTurnosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/registro_/callback': typeof RegistroCallbackRoute
  '/_authenticated/app/alumnos': typeof AuthenticatedAppAlumnosRoute
  '/_authenticated/app/archivos': typeof AuthenticatedAppArchivosRoute
  '/_authenticated/app/datos-personales': typeof AuthenticatedAppDatosPersonalesRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/evaluaciones': typeof AuthenticatedAppEvaluacionesRoute
  '/_authenticated/app/fichajes': typeof AuthenticatedAppFichajesRoute
  '/_authenticated/app/grupos': typeof AuthenticatedAppGruposRoute
  '/_authenticated/app/incidencias': typeof AuthenticatedAppIncidenciasRoute
  '/_authenticated/app/permisos': typeof AuthenticatedAppPermisosRoute
  '/_authenticated/app/prestamos': typeof AuthenticatedAppPrestamosRoute
  '/_authenticated/app/sesiones': typeof AuthenticatedAppSesionesRoute
  '/_authenticated/app/turnos': typeof AuthenticatedAppTurnosRoute
  '/_authenticated/profesores/mi-perfil': typeof AuthenticatedProfesoresMiPerfilRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/firmar-sepa'
    | '/login'
    | '/registro'
    | '/select-tenant'
    | '/alumnos'
    | '/alumnosMatriculas'
    | '/app'
    | '/aulas'
    | '/ausencias'
    | '/clientes'
    | '/comprasInternas'
    | '/dashboard'
    | '/documentos'
    | '/escuela'
    | '/especialidades'
    | '/evaluaciones'
    | '/facturas'
    | '/fichajes'
    | '/grupos'
    | '/incidencias'
    | '/leads'
    | '/matriculas'
    | '/mensajesAutomaticos'
    | '/prestamosMaterial'
    | '/profesores'
    | '/remesas'
    | '/rubricas'
    | '/sesiones'
    | '/tarifas'
    | '/turnos'
    | '/usuarios'
    | '/videos'
    | '/registro/callback'
    | '/app/alumnos'
    | '/app/archivos'
    | '/app/datos-personales'
    | '/app/documentos'
    | '/app/evaluaciones'
    | '/app/fichajes'
    | '/app/grupos'
    | '/app/incidencias'
    | '/app/permisos'
    | '/app/prestamos'
    | '/app/sesiones'
    | '/app/turnos'
    | '/profesores/mi-perfil'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/firmar-sepa'
    | '/login'
    | '/registro'
    | '/select-tenant'
    | '/alumnos'
    | '/alumnosMatriculas'
    | '/aulas'
    | '/ausencias'
    | '/clientes'
    | '/comprasInternas'
    | '/dashboard'
    | '/documentos'
    | '/escuela'
    | '/especialidades'
    | '/evaluaciones'
    | '/facturas'
    | '/fichajes'
    | '/grupos'
    | '/incidencias'
    | '/leads'
    | '/matriculas'
    | '/mensajesAutomaticos'
    | '/prestamosMaterial'
    | '/profesores'
    | '/remesas'
    | '/rubricas'
    | '/sesiones'
    | '/tarifas'
    | '/turnos'
    | '/usuarios'
    | '/videos'
    | '/registro/callback'
    | '/app/alumnos'
    | '/app/archivos'
    | '/app/datos-personales'
    | '/app/documentos'
    | '/app/evaluaciones'
    | '/app/fichajes'
    | '/app/grupos'
    | '/app/incidencias'
    | '/app/permisos'
    | '/app/prestamos'
    | '/app/sesiones'
    | '/app/turnos'
    | '/profesores/mi-perfil'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/firmar-sepa'
    | '/login'
    | '/registro'
    | '/select-tenant'
    | '/_authenticated/alumnos'
    | '/_authenticated/alumnosMatriculas'
    | '/_authenticated/app'
    | '/_authenticated/aulas'
    | '/_authenticated/ausencias'
    | '/_authenticated/clientes'
    | '/_authenticated/comprasInternas'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/escuela'
    | '/_authenticated/especialidades'
    | '/_authenticated/evaluaciones'
    | '/_authenticated/facturas'
    | '/_authenticated/fichajes'
    | '/_authenticated/grupos'
    | '/_authenticated/incidencias'
    | '/_authenticated/leads'
    | '/_authenticated/matriculas'
    | '/_authenticated/mensajesAutomaticos'
    | '/_authenticated/prestamosMaterial'
    | '/_authenticated/profesores'
    | '/_authenticated/remesas'
    | '/_authenticated/rubricas'
    | '/_authenticated/sesiones'
    | '/_authenticated/tarifas'
    | '/_authenticated/turnos'
    | '/_authenticated/usuarios'
    | '/_authenticated/videos'
    | '/registro_/callback'
    | '/_authenticated/app/alumnos'
    | '/_authenticated/app/archivos'
    | '/_authenticated/app/datos-personales'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/evaluaciones'
    | '/_authenticated/app/fichajes'
    | '/_authenticated/app/grupos'
    | '/_authenticated/app/incidencias'
    | '/_authenticated/app/permisos'
    | '/_authenticated/app/prestamos'
    | '/_authenticated/app/sesiones'
    | '/_authenticated/app/turnos'
    | '/_authenticated/profesores/mi-perfil'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FirmarSepaRoute: typeof FirmarSepaRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  SelectTenantRoute: typeof SelectTenantRoute
  RegistroCallbackRoute: typeof RegistroCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmar-sepa': {
      id: '/firmar-sepa'
      path: '/firmar-sepa'
      fullPath: '/firmar-sepa'
      preLoaderRoute: typeof FirmarSepaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro_/callback': {
      id: '/registro_/callback'
      path: '/registro/callback'
      fullPath: '/registro/callback'
      preLoaderRoute: typeof RegistroCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/turnos': {
      id: '/_authenticated/turnos'
      path: '/turnos'
      fullPath: '/turnos'
      preLoaderRoute: typeof AuthenticatedTurnosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarifas': {
      id: '/_authenticated/tarifas'
      path: '/tarifas'
      fullPath: '/tarifas'
      preLoaderRoute: typeof AuthenticatedTarifasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sesiones': {
      id: '/_authenticated/sesiones'
      path: '/sesiones'
      fullPath: '/sesiones'
      preLoaderRoute: typeof AuthenticatedSesionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rubricas': {
      id: '/_authenticated/rubricas'
      path: '/rubricas'
      fullPath: '/rubricas'
      preLoaderRoute: typeof AuthenticatedRubricasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/remesas': {
      id: '/_authenticated/remesas'
      path: '/remesas'
      fullPath: '/remesas'
      preLoaderRoute: typeof AuthenticatedRemesasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profesores': {
      id: '/_authenticated/profesores'
      path: '/profesores'
      fullPath: '/profesores'
      preLoaderRoute: typeof AuthenticatedProfesoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prestamosMaterial': {
      id: '/_authenticated/prestamosMaterial'
      path: '/prestamosMaterial'
      fullPath: '/prestamosMaterial'
      preLoaderRoute: typeof AuthenticatedPrestamosMaterialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensajesAutomaticos': {
      id: '/_authenticated/mensajesAutomaticos'
      path: '/mensajesAutomaticos'
      fullPath: '/mensajesAutomaticos'
      preLoaderRoute: typeof AuthenticatedMensajesAutomaticosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matriculas': {
      id: '/_authenticated/matriculas'
      path: '/matriculas'
      fullPath: '/matriculas'
      preLoaderRoute: typeof AuthenticatedMatriculasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidencias': {
      id: '/_authenticated/incidencias'
      path: '/incidencias'
      fullPath: '/incidencias'
      preLoaderRoute: typeof AuthenticatedIncidenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grupos': {
      id: '/_authenticated/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedGruposRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fichajes': {
      id: '/_authenticated/fichajes'
      path: '/fichajes'
      fullPath: '/fichajes'
      preLoaderRoute: typeof AuthenticatedFichajesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facturas': {
      id: '/_authenticated/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof AuthenticatedFacturasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evaluaciones': {
      id: '/_authenticated/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/evaluaciones'
      preLoaderRoute: typeof AuthenticatedEvaluacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/especialidades': {
      id: '/_authenticated/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof AuthenticatedEspecialidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/escuela': {
      id: '/_authenticated/escuela'
      path: '/escuela'
      fullPath: '/escuela'
      preLoaderRoute: typeof AuthenticatedEscuelaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comprasInternas': {
      id: '/_authenticated/comprasInternas'
      path: '/comprasInternas'
      fullPath: '/comprasInternas'
      preLoaderRoute: typeof AuthenticatedComprasInternasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ausencias': {
      id: '/_authenticated/ausencias'
      path: '/ausencias'
      fullPath: '/ausencias'
      preLoaderRoute: typeof AuthenticatedAusenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aulas': {
      id: '/_authenticated/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AuthenticatedAulasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alumnosMatriculas': {
      id: '/_authenticated/alumnosMatriculas'
      path: '/alumnosMatriculas'
      fullPath: '/alumnosMatriculas'
      preLoaderRoute: typeof AuthenticatedAlumnosMatriculasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alumnos': {
      id: '/_authenticated/alumnos'
      path: '/alumnos'
      fullPath: '/alumnos'
      preLoaderRoute: typeof AuthenticatedAlumnosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/profesores/mi-perfil': {
      id: '/_authenticated/profesores/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/profesores/mi-perfil'
      preLoaderRoute: typeof AuthenticatedProfesoresMiPerfilRouteImport
      parentRoute: typeof AuthenticatedProfesoresRoute
    }
    '/_authenticated/app/turnos': {
      id: '/_authenticated/app/turnos'
      path: '/turnos'
      fullPath: '/app/turnos'
      preLoaderRoute: typeof AuthenticatedAppTurnosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sesiones': {
      id: '/_authenticated/app/sesiones'
      path: '/sesiones'
      fullPath: '/app/sesiones'
      preLoaderRoute: typeof AuthenticatedAppSesionesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prestamos': {
      id: '/_authenticated/app/prestamos'
      path: '/prestamos'
      fullPath: '/app/prestamos'
      preLoaderRoute: typeof AuthenticatedAppPrestamosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/permisos': {
      id: '/_authenticated/app/permisos'
      path: '/permisos'
      fullPath: '/app/permisos'
      preLoaderRoute: typeof AuthenticatedAppPermisosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/incidencias': {
      id: '/_authenticated/app/incidencias'
      path: '/incidencias'
      fullPath: '/app/incidencias'
      preLoaderRoute: typeof AuthenticatedAppIncidenciasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/grupos': {
      id: '/_authenticated/app/grupos'
      path: '/grupos'
      fullPath: '/app/grupos'
      preLoaderRoute: typeof AuthenticatedAppGruposRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/fichajes': {
      id: '/_authenticated/app/fichajes'
      path: '/fichajes'
      fullPath: '/app/fichajes'
      preLoaderRoute: typeof AuthenticatedAppFichajesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/evaluaciones': {
      id: '/_authenticated/app/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/app/evaluaciones'
      preLoaderRoute: typeof AuthenticatedAppEvaluacionesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/datos-personales': {
      id: '/_authenticated/app/datos-personales'
      path: '/datos-personales'
      fullPath: '/app/datos-personales'
      preLoaderRoute: typeof AuthenticatedAppDatosPersonalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/archivos': {
      id: '/_authenticated/app/archivos'
      path: '/archivos'
      fullPath: '/app/archivos'
      preLoaderRoute: typeof AuthenticatedAppArchivosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alumnos': {
      id: '/_authenticated/app/alumnos'
      path: '/alumnos'
      fullPath: '/app/alumnos'
      preLoaderRoute: typeof AuthenticatedAppAlumnosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAlumnosRoute: typeof AuthenticatedAppAlumnosRoute
  AuthenticatedAppArchivosRoute: typeof AuthenticatedAppArchivosRoute
  AuthenticatedAppDatosPersonalesRoute: typeof AuthenticatedAppDatosPersonalesRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppEvaluacionesRoute: typeof AuthenticatedAppEvaluacionesRoute
  AuthenticatedAppFichajesRoute: typeof AuthenticatedAppFichajesRoute
  AuthenticatedAppGruposRoute: typeof AuthenticatedAppGruposRoute
  AuthenticatedAppIncidenciasRoute: typeof AuthenticatedAppIncidenciasRoute
  AuthenticatedAppPermisosRoute: typeof AuthenticatedAppPermisosRoute
  AuthenticatedAppPrestamosRoute: typeof AuthenticatedAppPrestamosRoute
  AuthenticatedAppSesionesRoute: typeof AuthenticatedAppSesionesRoute
  AuthenticatedAppTurnosRoute: typeof AuthenticatedAppTurnosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAlumnosRoute: AuthenticatedAppAlumnosRoute,
  AuthenticatedAppArchivosRoute: AuthenticatedAppArchivosRoute,
  AuthenticatedAppDatosPersonalesRoute: AuthenticatedAppDatosPersonalesRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppEvaluacionesRoute: AuthenticatedAppEvaluacionesRoute,
  AuthenticatedAppFichajesRoute: AuthenticatedAppFichajesRoute,
  AuthenticatedAppGruposRoute: AuthenticatedAppGruposRoute,
  AuthenticatedAppIncidenciasRoute: AuthenticatedAppIncidenciasRoute,
  AuthenticatedAppPermisosRoute: AuthenticatedAppPermisosRoute,
  AuthenticatedAppPrestamosRoute: AuthenticatedAppPrestamosRoute,
  AuthenticatedAppSesionesRoute: AuthenticatedAppSesionesRoute,
  AuthenticatedAppTurnosRoute: AuthenticatedAppTurnosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedProfesoresRouteChildren {
  AuthenticatedProfesoresMiPerfilRoute: typeof AuthenticatedProfesoresMiPerfilRoute
}

const AuthenticatedProfesoresRouteChildren: AuthenticatedProfesoresRouteChildren =
  {
    AuthenticatedProfesoresMiPerfilRoute: AuthenticatedProfesoresMiPerfilRoute,
  }

const AuthenticatedProfesoresRouteWithChildren =
  AuthenticatedProfesoresRoute._addFileChildren(
    AuthenticatedProfesoresRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlumnosRoute: typeof AuthenticatedAlumnosRoute
  AuthenticatedAlumnosMatriculasRoute: typeof AuthenticatedAlumnosMatriculasRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedAulasRoute: typeof AuthenticatedAulasRoute
  AuthenticatedAusenciasRoute: typeof AuthenticatedAusenciasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComprasInternasRoute: typeof AuthenticatedComprasInternasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEscuelaRoute: typeof AuthenticatedEscuelaRoute
  AuthenticatedEspecialidadesRoute: typeof AuthenticatedEspecialidadesRoute
  AuthenticatedEvaluacionesRoute: typeof AuthenticatedEvaluacionesRoute
  AuthenticatedFacturasRoute: typeof AuthenticatedFacturasRoute
  AuthenticatedFichajesRoute: typeof AuthenticatedFichajesRoute
  AuthenticatedGruposRoute: typeof AuthenticatedGruposRoute
  AuthenticatedIncidenciasRoute: typeof AuthenticatedIncidenciasRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMatriculasRoute: typeof AuthenticatedMatriculasRoute
  AuthenticatedMensajesAutomaticosRoute: typeof AuthenticatedMensajesAutomaticosRoute
  AuthenticatedPrestamosMaterialRoute: typeof AuthenticatedPrestamosMaterialRoute
  AuthenticatedProfesoresRoute: typeof AuthenticatedProfesoresRouteWithChildren
  AuthenticatedRemesasRoute: typeof AuthenticatedRemesasRoute
  AuthenticatedRubricasRoute: typeof AuthenticatedRubricasRoute
  AuthenticatedSesionesRoute: typeof AuthenticatedSesionesRoute
  AuthenticatedTarifasRoute: typeof AuthenticatedTarifasRoute
  AuthenticatedTurnosRoute: typeof AuthenticatedTurnosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlumnosRoute: AuthenticatedAlumnosRoute,
  AuthenticatedAlumnosMatriculasRoute: AuthenticatedAlumnosMatriculasRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedAulasRoute: AuthenticatedAulasRoute,
  AuthenticatedAusenciasRoute: AuthenticatedAusenciasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComprasInternasRoute: AuthenticatedComprasInternasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEscuelaRoute: AuthenticatedEscuelaRoute,
  AuthenticatedEspecialidadesRoute: AuthenticatedEspecialidadesRoute,
  AuthenticatedEvaluacionesRoute: AuthenticatedEvaluacionesRoute,
  AuthenticatedFacturasRoute: AuthenticatedFacturasRoute,
  AuthenticatedFichajesRoute: AuthenticatedFichajesRoute,
  AuthenticatedGruposRoute: AuthenticatedGruposRoute,
  AuthenticatedIncidenciasRoute: AuthenticatedIncidenciasRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMatriculasRoute: AuthenticatedMatriculasRoute,
  AuthenticatedMensajesAutomaticosRoute: AuthenticatedMensajesAutomaticosRoute,
  AuthenticatedPrestamosMaterialRoute: AuthenticatedPrestamosMaterialRoute,
  AuthenticatedProfesoresRoute: AuthenticatedProfesoresRouteWithChildren,
  AuthenticatedRemesasRoute: AuthenticatedRemesasRoute,
  AuthenticatedRubricasRoute: AuthenticatedRubricasRoute,
  AuthenticatedSesionesRoute: AuthenticatedSesionesRoute,
  AuthenticatedTarifasRoute: AuthenticatedTarifasRoute,
  AuthenticatedTurnosRoute: AuthenticatedTurnosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FirmarSepaRoute: FirmarSepaRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  SelectTenantRoute: SelectTenantRoute,
  RegistroCallbackRoute: RegistroCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
