-- CLIENTES: lectura por columnas seguras (sin STRIPE_API_KEY ni KOREFACTU_API_KEY).
-- Idempotente: REVOKE tabla + GRANT columnas (re-ejecutable tras hotfix manual).

REVOKE SELECT ON public."CLIENTES" FROM authenticated;

GRANT SELECT (
  "ID_CLIENTE",
  "NOMBRE_ESCUELA",
  "TLF_REAL",
  "URL_WEB",
  "EMAIL_CLIENTE",
  "APP_LOGO",
  "CIF",
  "DIRECCION",
  "ESTADO_CLIENTE",
  "PLAN",
  "METODO_PAGO_PROPIO",
  "PAGO",
  "TARIFA",
  "FECHA_PROXIMO_PLAN",
  "NOMINAS",
  "SECRETARIA",
  "MONTAJE",
  "MONTAJE_PENDIENTE",
  "DESCUENTO",
  "TIPO_COBRO",
  "ESTADO_MANDATO",
  "IBAN",
  "STRIPE_ID",
  "DOCUMENTO_SEPA",
  "KOREFACTU_BASE_URL",
  "REGLA_COBRO_MATRICULA",
  "IDENTIFICADOR_ACREEDOR",
  "DEMO_CAL_MEETING_AT",
  "DEMO_CAL_BOOKING_UID",
  "DEMO_TRIAL_STARTED_AT",
  "TEXTO_REGIMEN_INTERNO",
  "TEXTO_AUT_MEDIOS",
  "TEXTO_AUT_INSTALACIONES",
  "TEXTO_AUT_WEB",
  "TEXTO_AUT_RRSS",
  "TEXTO_AUT_COMUNICACION"
) ON public."CLIENTES" TO authenticated;
