-- Duplicado conocido: ESC_004_ALU_0017 + HORARIO_ESTIM_MIERCOLES (ESC_004_HM_0027, ESC_004_HM_0028).

DELETE FROM public."HORARIOS_MATRICULAS"
WHERE "ID_HORARIO" IN ('ESC_004_HM_0027', 'ESC_004_HM_0028');

CREATE UNIQUE INDEX IF NOT EXISTS horarios_matriculas_alumno_grupo_horario_uidx
  ON public."HORARIOS_MATRICULAS" ("ID_ALUMNO", "ID_GRUPO_HORARIO")
  WHERE "ID_GRUPO_HORARIO" IS NOT NULL;
